---
  - name: MatomoPlaybook
    hosts: matomo2
    become: yes
    become_user: root
    tasks:
      - name: Install Apache, PHP, MySQL, Unzip
        apt:
          pkg:
            - apache2
            - mysql-server
            - php7.4
            - libapache2-mod-php7.4
            - php7.4-json
            - php7.4-curl
            - php7.4-mysql
            - php7.4-xml
            - php7.4-zip
            - php7.4-intl
            - php7.4-gd
            - php7.4-cli
            - php7.4-mbstring
            - unzip
          force_apt_get: true
          update_cache: yes

      - name: Upgrade all packages to the latest version
        apt:
          name: "*"
          state: latest
          force_apt_get: true

      - name: Download Matomo
        get_url:
          url: https://builds.matomo.org/matomo-latest.zip
          dest: /home/agiskourle

      - name: Create the installation directory
        file:
          path: /var/www/matomo
          state: directory

      - name: Extract matomo zip file
        unarchive:
          src: /home/agiskourle/matomo-latest.zip
          dest: /home/agiskourle/
          remote_src: yes
  
      - name: Copy files to matomo directory
        copy:
          src: /home/agiskourle/matomo/
          dest: /var/www/matomo
          remote_src: yes

      - name: Recursively change ownership of the matomo directory
        file:
          path: /var/www/matomo
          state: directory
          recurse: yes
          owner: www-data
          group: www-data
          mode: '755'
          
      - name: Start MySQL
        service:
          name: mysql
          state: started
          enabled: yes

      - name: Create matomo database
        mysql_db:
          name: matomo
          state: present
          check_implicit_admin: yes
          login_unix_socket: /var/run/mysqld/mysqld.sock
          #login_user: root
          #login_password: mysql_root_password  

      - name: Create database user
        mysql_user:
          name: matomouser
          password: StrongPassword
          priv: '*.*:ALL'
          state: present
          check_implicit_admin: yes
          login_unix_socket: /var/run/mysqld/mysqld.sock
          #login_user: root
          #login_password: mysql_root_password

      - name: Create matomo.conf file
        copy:
          dest: /etc/apache2/sites-available/matomo.conf
          content: |
            <VirtualHost *:80>
             ServerAdmin admin@example.com
             ServerName example.com
             DocumentRoot /var/www/matomo/

             <Directory /var/www/matomo>
             DirectoryIndex index.php
             Options FollowSymLinks
             AllowOverride All
             Require all granted
             </Directory>

             <Files "console">
             Options None
             Require all denied
             </Files>

             <Directory /var/www/matomo/misc/user>
             Options None
             Require all granted
             </Directory>

             <Directory /var/www/matomo/misc>
             Options None
             Require all denied
             </Directory>

             <Directory /var/www/matomo/vendor>
             Options None
             Require all denied
             </Directory>

             ErrorLog ${APACHE_LOG_DIR}/matomo_error.log
             CustomLog ${APACHE_LOG_DIR}/matomo_access.log combined

             </VirtualHost>

      - name: Disable default Apache SSL site
        command: a2dissite 000-default.conf

      - name: Enable matomo.conf
        command: a2ensite matomo.conf

      - name: Enable rewrite mode
        command: a2enmod rewrite

      - name: Restart Apache
        service:
          name: apache2
          state: restarted
          enabled: yes